version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge
    restart: on-failure
    ports:
      - "1434:1433"
    environment:
        SA_PASSWORD: "password"
        ACCEPT_EULA: "Y"
    
  web-api:
    depends_on: 
      - sql-server
    restart: on-failure
    environment:
        ASPNETCORE_ENVIRONMENT: "Docker-sql"
    build: .
    ports:
      - "8161:80"
