services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      LOCALSTACK_SERVICES: s3
      LOCALSTACK_PERSISTENCE: 1
      LOCALSTACK_AWS_SECRET_ACCESS_KEY: test
      LOCALSTACK_AWS_ACCESS_KEY_ID: test
      LOCALSTACK_REGION: us-east-1
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range

  sqlserver:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "MySuperStrongPassword1(!)"
      MSSQL_USER: "sa"
      ACCEPT_EULA: "Y"
    ports:
      - "1430:1433"

  webapi:
    container_name: web-api
    build: .
    image: cq-auth-provider-webapi
    ports:
      - "7190:7190" 
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__Auth: "Server=sqlserver,1433; Database=AuthProvider; User ID=sa; Password=MySuperStrongPassword1(!); TrustServerCertificate=true;"
      ConnectionStrings__Identity: "Server=sqlserver,1433; Database=IdentityProvider; User ID=sa; Password=MySuperStrongPassword1(!); TrustServerCertificate=true;"
      DatabaseEngine__Auth: "Sql"
      DatabaseEngine__Identity: "Sql"
      Authentication__Type: "LocalStack"
      Blob__Config__AccessToken: "test"
      Blob__Config__SecretToken: "test"
      Blob__Config__ServiceUrl: "http://192.168.0.106:4566"
      ASPNETCORE_HTTP_PORTS: 7190
      # ASPNETCORE_URLS: http://*:80
    depends_on:
      - sqlserver
      - localstack