version: '3.8'

services:
  sqlserver:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "MySuperStrongPassword1(!)"
      MSSQL_USER: "sa"
      ACCEPT_EULA: "Y"
    ports:
      - "1430:1433"

  webapi:
    container_name: web-api
    build: .
    image: cq-auth-provider-webapi
    ports:
      - "7190:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Local"
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_URLS: http://*:80
    depends_on:
      - sqlserver
