version: '3'
services:
  mongo-server:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
  web-api:
    restart: always
    env_file:
      - CQ.AuthProvider.WebApi/.env
    build: .
    ports:
      - "7049:80"