version: '3'
services:
  mongo-server:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
  web-api:
    depends_on: 
      - mongo-server
    restart: always
    env_file:
      - CQ.AuthProvider.WebApi/.env.docker.local
    build: .
    ports:
      - "8161:80"