services:
  sqlserver:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "MySuperStrongPassword1(!)"
      MSSQL_USER: "sa"
      ACCEPT_EULA: "Y"
    ports:
      - "1430:1433"

  webapi:
    container_name: web-api
    build: .
    image: cq-auth-provider-webapi
    ports:
      - "7190:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Local"
      ConnectionStrings__Auth: "Server=sqlserver,1433; Database=AuthProvider; User ID=sa; Password=MySuperStrongPassword1(!); TrustServerCertificate=true;"
      ConnectionStrings__Identity: "Server=sqlserver,1433; Database=IdentityProvider; User ID=sa; Password=MySuperStrongPassword1(!); TrustServerCertificate=true;"
      # ASPNETCORE_HTTP_PORTS: 80
      # ASPNETCORE_URLS: http://*:80
    depends_on:
      - sqlserver
