# name: Deploy
 
# on:
#   push:
#     branches:
#       - main
 
# permissions:
#   contents: read
#   id-token: write
 
# env:
#   DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
#   AWS_REGION: us-east-1
#   AWS_EKS_CLUSTER_NAME: ekscluster
 
# jobs:
#   cd:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
 
#       - name: AWS Authenticate
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}
 
#       - name: Login AWS ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1
 
#       - name: Docker Build and Push
#         env:
#           DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
#           IMAGE_TAG: latest
#         run: |
#           docker build -t $DOCKER_REPO:$IMAGE_TAG .
#           docker push $DOCKER_REPO:$IMAGE_TAG
 
